language: php

php:
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"

before_script:
  - composer install --prefer-dist --dev

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

script:
  - ./vendor/bin/phpunit --stderr
  - ./vendor/bin/phpcs
